name: Save Order via Issues

on:
  issues:
    types: [opened]

jobs:
  process-order:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.body, 'ORDER_DATA:')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Extract and Save Order
        run: |
          # Extract order data between markers
          ORDER_DATA=$(echo "${{ github.event.issue.body }}" | sed -n '/ORDER_DATA:/,/END_ORDER_DATA/p' | sed '1d;$d')
          
          # Generate timestamp for unique filename
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          
          # Create orders directory if it doesn't exist
          mkdir -p docs/orders
          
          # Save order data to JSON file
          echo "$ORDER_DATA" > "docs/orders/order_${TIMESTAMP}.json"
          
          # Configure Git
          git config user.name "GitHub Action Bot"
          git config user.email "action@github.com"
          
          # Stage, commit and push changes
          git add docs/orders/
          git commit -m "New order saved: ${TIMESTAMP}"
          git push origin HEAD

      - name: Add Processing Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ✅ Order has been processed and saved.
            
            Order details have been securely stored in the system.
            Thank you for your purchase!

      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Order processing completed.